import { Container, Typography, Button, Box, Card, CardContent, Paper, Accordion, AccordionSummary, AccordionDetails, Grid, Fade, useTheme } from "@mui/material";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
import GraphicEqIcon from "@mui/icons-material/GraphicEq";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import { useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";

const steps = [
    { title: "Upload", description: "Upload an MP3/WAV file for analysis.", icon: <CloudUploadIcon fontSize="large" color="primary" /> },
    { title: "Analysis", description: "Our AI model processes the audio file.", icon: <GraphicEqIcon fontSize="large" color="secondary" /> },
    { title: "Results", description: "View the deepfake probability score.", icon: <CheckCircleIcon fontSize="large" color="success" /> },
];

const faqs = [
    {
        question: "How accurate is the deepfake detection?",
        answer: "Our model achieves over 90% accuracy on benchmark datasets. However, as deepfake technology evolves, we continuously improve our detection algorithms."
    },
    {
        question: "What audio formats are supported?",
        answer: "Currently, we support MP3 and WAV file formats. We're working on expanding to additional audio formats in future updates."
    },
    {
        question: "Is my audio data kept private?",
        answer: "Yes, privacy is our priority. Your uploaded audio files are processed securely and are not stored permanently on our servers after analysis."
    },
    {
        question: "How does the detection technology work?",
        answer: "Our AI uses advanced machine learning techniques to analyze acoustic patterns, voice characteristics, and other subtle features that distinguish real from synthetic audio."
    }
];

export default function LandingPage() {
    const navigate = useNavigate();
    const [fadeIn, setFadeIn] = useState(false);
    const theme = useTheme();

    useEffect(() => {
        setFadeIn(true);
    }, []);

    return (
        <>
            {/*Hero Section*/}
            <Fade in={fadeIn} timeout={1000}>
                <Box sx={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "center",
                    alignItems: "center",
                    padding: "20px",
                    marginBottom: 4
                }}>
                    <Paper elevation={3} sx={{
                        width: { xs: "95%", sm: "90%", md: "85%" },
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        gap: 2,
                        p: { xs: 3, md: 4 },
                        mt: 2,
                        borderRadius: "12px",
                        bgcolor: "background.paper"
                    }}>
                        <Typography variant="h3" fontWeight="bold" color="primary" sx={{ fontSize: { xs: "1.8rem", sm: "2.2rem", md: "2.5rem" } }}>
                            What is this tool?🤔
                        </Typography>
                        <Typography variant="h5" align="center" color="text.primary" sx={{ fontSize: { xs: "1.2rem", sm: "1.4rem", md: "1.5rem" } }}>
                            This is an Audio Deepfake Detector Tool - Fake Breaker🎉
                        </Typography>
                        <Typography variant="h5" align="center" color="text.primary" sx={{ fontSize: { xs: "1.2rem", sm: "1.4rem", md: "1.5rem" } }}>
                            It detects if an audio file is authentic or generated by AI.
                        </Typography>

                        <Typography variant="h3" fontWeight="bold" color="primary" mt={4} sx={{ fontSize: { xs: "1.8rem", sm: "2.2rem", md: "2.5rem" } }}>
                            Why is it needed?🧐
                        </Typography>
                        <Typography variant="h5" align="center" color="text.primary" sx={{ fontSize: { xs: "1.2rem", sm: "1.4rem", md: "1.5rem" } }}>
                            It's a critical tool for today's digital landscape.
                        </Typography>
                        <Typography variant="h5" align="center" color="text.primary" sx={{ fontSize: { xs: "1.2rem", sm: "1.4rem", md: "1.5rem" } }}>
                            With the advent of Deepfake Generation, fake media is getting pinpoint accurate day-by-day.
                        </Typography>
                        <Typography variant="h5" align="center" color="text.primary" sx={{ fontSize: { xs: "1.2rem", sm: "1.4rem", md: "1.5rem" } }}>
                            It is important to not get duped by any fake audio.
                        </Typography>

                        <Typography variant="h4" align="center" color="text.primary" mt={3} sx={{ fontSize: { xs: "1.3rem", sm: "1.6rem", md: "1.8rem" } }}>
                            So next time when you receive any suspicious audio...
                            <Typography variant="h4" align="center" color="text.primary" sx={{ fontSize: { xs: "1.3rem", sm: "1.6rem", md: "1.8rem" } }}>
                                just jump over here and get it analyzed.😎
                            </Typography>
                        </Typography>
                        <Typography variant="h6" m={3} fontWeight={'bold'} align="center" color="text.primary">
                            Let's fight the digital deception together!💪
                        </Typography>

                        <Button
                            variant="contained"
                            size="large"
                            onClick={() => navigate("/upload")}
                            sx={{
                                mt: 2,
                                py: 1.5,
                                px: 4,
                                borderRadius: "30px",
                                fontSize: "1.1rem",
                                fontWeight: "bold",
                                boxShadow: "0 4px 10px rgba(0, 0, 0, 0.15)",
                                background: theme.palette.mode === 'dark'
                                    ? "linear-gradient(90deg, #2196F3 0%, #64B5F6 100%)"
                                    : "linear-gradient(90deg, #1976D2 0%, #42A5F5 100%)",
                                transition: "transform 0.3s ease-in-out",
                                "&:hover": {
                                    transform: "scale(1.05)",
                                    background: theme.palette.mode === 'dark'
                                        ? "linear-gradient(90deg, #1E88E5 0%, #2196F3 100%)"
                                        : "linear-gradient(90deg, #1565C0 0%, #1976D2 100%)",
                                }
                            }}
                        >
                            Try It Now
                        </Button>
                    </Paper>
                </Box>
            </Fade>

            {/* How It Works - Three-Step Card Layout using Box with CSS Grid */}
            <Container
                maxWidth="md"
                sx={{ mt: { xs: 3, md: 5 }, px: { xs: 2, md: 0 }, mb: 6 }}
            >
                <Typography
                    variant="h4"
                    textAlign="center"
                    fontWeight="bold"
                    mb={4}
                    sx={{ fontSize: { xs: "1.5rem", md: "2rem" } }}
                    color="primary"
                >
                    How It Works
                </Typography>
                <Box
                    sx={{
                        display: "grid",
                        gap: 3,
                        gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr", md: "repeat(3, 1fr)" }
                    }}
                >
                    {steps.map((step, index) => (
                        <Card
                            key={index}
                            sx={{
                                textAlign: "center",
                                p: { xs: 2, sm: 2.5, md: 3 },
                                height: "100%",
                                borderRadius: "10px",
                                bgcolor: "background.paper",
                                transition: "transform 0.3s ease, box-shadow 0.3s ease",
                                "&:hover": {
                                    transform: "translateY(-8px)",
                                    boxShadow: "0 12px 20px rgba(0, 0, 0, 0.15)"
                                }
                            }}
                        >
                            <CardContent>
                                <Box sx={{ mb: 2 }}>
                                    {step.icon}
                                </Box>
                                <Typography
                                    variant="h6"
                                    fontWeight="bold"
                                    mt={2}
                                    color="text.primary"
                                    sx={{ fontSize: { xs: "1.1rem", md: "1.3rem" } }}
                                >
                                    {step.title}
                                </Typography>
                                <Typography
                                    variant="body1"
                                    color="text.secondary"
                                    mt={1.5}
                                    sx={{ fontSize: { xs: "0.9rem", md: "1rem" } }}
                                >
                                    {step.description}
                                </Typography>
                            </CardContent>
                        </Card>
                    ))}
                </Box>
            </Container>

            {/* Demo Section */}
            <Container maxWidth="md" sx={{ mb: 6 }}>
                <Paper
                    elevation={2}
                    sx={{
                        p: { xs: 2, md: 4 },
                        borderRadius: "10px",
                        bgcolor: theme.palette.mode === 'dark' ? 'background.paper' : "#f5f9ff"
                    }}
                >
                    <Typography
                        variant="h4"
                        textAlign="center"
                        fontWeight="bold"
                        mb={3}
                        color="primary"
                        sx={{ fontSize: { xs: "1.5rem", md: "2rem" } }}
                    >
                        See It In Action
                    </Typography>

                    <Grid container spacing={3} alignItems="center">
                        <Grid item xs={12} md={6}>
                            <Typography variant="h6" color="text.primary" gutterBottom sx={{ fontSize: { xs: "1rem", md: "1.2rem" } }}>
                                Our detection system can identify:
                            </Typography>
                            <Box component="ul" sx={{ pl: 2 }}>
                                <Typography component="li" variant="body1" color="text.primary" sx={{ mb: 1 }}>
                                    Voice cloning and synthesis
                                </Typography>
                                <Typography component="li" variant="body1" color="text.primary" sx={{ mb: 1 }}>
                                    Edited or spliced audio content
                                </Typography>
                                <Typography component="li" variant="body1" color="text.primary" sx={{ mb: 1 }}>
                                    AI-generated speech patterns
                                </Typography>
                                <Typography component="li" variant="body1" color="text.primary">
                                    Manipulated emotional tones
                                </Typography>
                            </Box>
                            <Button
                                variant="outlined"
                                color="primary"
                                sx={{ mt: 2 }}
                                onClick={() => navigate("/upload")}
                            >
                                Try With Your Audio
                            </Button>
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Box
                                sx={{
                                    borderRadius: "10px",
                                    height: "200px",
                                    bgcolor: theme.palette.mode === 'dark' ? 'background.paper' : "#e0e0e0",
                                    display: "flex",
                                    alignItems: "center",
                                    justifyContent: "center"
                                }}
                            >
                                <Typography variant="body1" color="text.secondary">
                                    Accuracy Visualization Placeholder
                                </Typography>
                            </Box>
                            <Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 1, textAlign: "center" }}>
                                Our model provides detailed analysis with confidence scores
                            </Typography>
                        </Grid>
                    </Grid>
                </Paper>
            </Container>

            {/* FAQ Section */}
            <Container maxWidth="md" sx={{ mb: 6 }}>
                <Typography
                    variant="h4"
                    textAlign="center"
                    fontWeight="bold"
                    mb={4}
                    color="primary"
                    sx={{ fontSize: { xs: "1.5rem", md: "2rem" } }}
                >
                    Frequently Asked Questions
                </Typography>

                {faqs.map((faq, index) => (
                    <Accordion
                        key={index}
                        sx={{
                            mb: 1,
                            borderRadius: "8px",
                            overflow: "hidden",
                            bgcolor: "background.paper"
                        }}
                    >
                        <AccordionSummary
                            expandIcon={<ExpandMoreIcon />}
                            sx={{
                                bgcolor: theme.palette.mode === 'dark' ? 'background.paper' : "#f5f9ff",
                                "&:hover": {
                                    bgcolor: theme.palette.mode === 'dark' ? 'action.hover' : "#e8f4ff"
                                }
                            }}
                        >
                            <Typography variant="h6" color="text.primary" sx={{ fontSize: { xs: "1rem", md: "1.1rem" } }}>
                                {faq.question}
                            </Typography>
                        </AccordionSummary>
                        <AccordionDetails>
                            <Typography variant="body1" color="text.primary">
                                {faq.answer}
                            </Typography>
                        </AccordionDetails>
                    </Accordion>
                ))}
            </Container>

            {/* CTA Section */}
            <Container
                maxWidth="md"
                sx={{
                    textAlign: "center",
                    mt: { xs: 2, md: 5 },
                    py: { xs: 4, md: 6 },
                    px: { xs: 2, md: 4 },
                    background: theme.palette.mode === 'dark'
                        ? "linear-gradient(135deg,rgb(14, 141, 245) 30%,rgb(60, 146, 216) 90%)"
                        : "linear-gradient(135deg, #1976D2 30%,rgb(36, 140, 224) 90%)",
                    borderRadius: "15px",
                    color: "white",
                    mb: 6
                }}
            >
                <Typography
                    variant="h4"
                    gutterBottom
                    fontWeight="bold"
                    sx={{ fontSize: { xs: "1.8rem", md: "2.5rem" } }}
                >
                    Detect Audio Deepfakes with AI
                </Typography>
                <Typography
                    variant="body1"
                    sx={{ fontSize: { xs: "0.9rem", md: "1.2rem" }, mb: { xs: 2, md: 3 }, maxWidth: "700px", mx: "auto" }}
                >
                    Upload an audio file and let our AI analyze it for deepfake characteristics in seconds.
                    Protect yourself and others from misinformation.
                </Typography>
                <Button
                    variant="contained"
                    size="large"
                    sx={{
                        backgroundColor: "white",
                        color: theme.palette.primary.main,
                        fontWeight: "bold",
                        mt: 2,
                        py: 1.5,
                        px: 4,
                        borderRadius: "30px",
                        boxShadow: "0 4px 10px rgba(0, 0, 0, 0.15)",
                        transition: "transform 0.2s ease-out",
                        "&:hover": {
                            transform: "scale(1.04)",
                            backgroundColor: theme.palette.mode === 'dark' ? "#f0f0f0" : "#f5f5f5"
                        },
                        width: { xs: "100%", sm: "auto" }
                    }}
                    onClick={() => navigate("/upload")}
                >
                    Upload & Analyse Now
                </Button>
            </Container>
        </>
    );
}

