import React from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Paper, Typography, Button, Box, LinearProgress, Divider, Container } from "@mui/material";
import { CheckCircleOutline, WarningAmber } from "@mui/icons-material";

const ResultsPage = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const { result, fileName } = location.state || {};

    // If no result data exists, redirect back to upload page
    if (!result) {
        navigate("/");
        return null;
    }

    const normalizedLabel = result.result_label ? result.result_label.toLowerCase() : "";
    const isReal = normalizedLabel === "real";

    return (
        <Container maxWidth="sm" sx={{ mt: 5, textAlign: "center" }}>
            <Paper elevation={3} sx={{ p: { xs: 3, md: 5 }, borderRadius: "12px" }}>
                <Typography variant="h4" fontWeight="bold" color="#1976D2" gutterBottom>
                    Analysis Results
                </Typography>
                <Divider sx={{ my: 2 }} />
                <Typography variant="subtitle1" color="textSecondary">
                    File name: {fileName}
                </Typography>

                {/* Result Icon & Label */}
                <Box mt={3} display="flex" flexDirection="column" alignItems="center">
                    {isReal ? (
                        <CheckCircleOutline sx={{ fontSize: 60, color: "green" }} />
                    ) : (
                        <WarningAmber sx={{ fontSize: 60, color: "red" }} />
                    )}
                    <Typography variant="h5" sx={{ mt: 1, fontWeight: "bold" }}>
                        {result.result_label}
                    </Typography>
                </Box>

                {/* Probability Bars */}
                <Box textAlign="left" mt={3}>
                    <Typography variant="h6">Fake Probability</Typography>
                    <LinearProgress
                        variant="determinate"
                        value={result.fake_probability}
                        sx={{
                            height: 10,
                            borderRadius: 5,
                            backgroundColor: "#ccc",
                            "& .MuiLinearProgress-bar": { backgroundColor: "red" },
                        }}
                    />
                    <Typography variant="body2" sx={{ mt: 1 }}>
                        {result.fake_probability.toFixed(2)}%
                    </Typography>

                    <Typography variant="h6" sx={{ mt: 2 }}>
                        Real Probability
                    </Typography>
                    <LinearProgress
                        variant="determinate"
                        value={result.real_probability}
                        sx={{
                            height: 10,
                            borderRadius: 5,
                            backgroundColor: "#ccc",
                            "& .MuiLinearProgress-bar": { backgroundColor: "green" },
                        }}
                    />
                    <Typography variant="body2" sx={{ mt: 1 }}>
                        {result.real_probability.toFixed(2)}%
                    </Typography>
                </Box>

                {/* Back to Upload Button */}
                <Button
                    variant="contained"
                    sx={{
                        mt: 3,
                        backgroundColor: "#1976D2",
                        width: "100%",
                        maxWidth: 300,
                    }}
                    onClick={() => navigate("/upload")}
                >
                    Back to Upload
                </Button>
            </Paper>

            {/* Disclaimer Section */}
            <Paper elevation={3} sx={{ p: 2, mt: 3, backgroundColor: "#f9f9f9", borderRadius: "8px" }}>
                <Typography variant="body2" color="error" fontWeight="bold">
                    Disclaimer: The results generated by the detector may not always be accurate, but they provide a strong indication!
                </Typography>
            </Paper>
        </Container>
    );
};

export default ResultsPage;
